[build]
  publish = "public"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:branch"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
